import { StyleSheet } from 'react-native';

export const globalStyles = StyleSheet.create({
  boldText: {
    fontFamily: 'lato-bold'
  }
})

export const images = {
  herbs: {
    "AgnusCastus": require('../assets/herbs/chaste-tree.jpg'),
    "Ashwagandha": require('../assets/herbs/ashwagandha.jpg'),
    "Barberry": require('../assets/herbs/barberry.jpg'),
    "BlueFlag": require('../assets/herbs/blue-flag.jpg'),
    "Borage": require('../assets/herbs/borage.jpg'),
    "Burdock": require('../assets/herbs/burdock.jpg'),
    "CalifornianPoppy": require('../assets/herbs/californian-poppy.jpg'),
    "Celery": require('../assets/herbs/celery.jpeg'),
    "Chamomile": require('../assets/herbs/chamomile.jpg'),
    "Chickweed": require('../assets/herbs/chickweed.jpg'),
    "Cleavers": require('../assets/herbs/cleavers.jpg'),
    "Comfrey": require('../assets/herbs/comfrey.jpg'),
    "Catnip": require('../assets/herbs/catnip.jpg'),
    "CrampBark": require('../assets/herbs/cramp-bark.jpg'),
    "Dandelion": require('../assets/herbs/tarax2.jpg'),
    "Echinacea": require('../assets/herbs/echinacea.jpg'),
    "Elder": require('../assets/herbs/elder.jpg'),
    "Elecampane": require('../assets/herbs/elecampagne.jpg'),
    "Ginger": require('../assets/herbs/ginger.jpg'),
    "Ginkgo": require('../assets/herbs/ginkgo.jpg'),
    "GlobeArtichoke": require('../assets/herbs/globe-artichoke.jpg'),
    "GoldenRod": require('../assets/herbs/golden-rod.jpg'),
    "Hawthorn": require('../assets/herbs/hawthorn.jpg'),
    "Heartsease": require('../assets/herbs/heartsease.jpg'),
    "Horsetail": require('../assets/herbs/horsetail.jpg'),
    "LadysMantle": require('../assets/herbs/ladys-mantle.jpg'),
    "Lavender": require('../assets/herbs/lavender.jpg'),
    "LemonBalm": require('../assets/herbs/lemon-balm.jpg'),
    "Limeflowers": require('../assets/herbs/limeflowers.jpg'),
    "Marigold": require('../assets/herbs/marigold.jpg'),
    "Marshmallow": require('../assets/herbs/marshmallow.jpg'),
    "Meadowsweet": require('../assets/herbs/meadowsweet.jpg'),
    "Motherwort": require('../assets/herbs/motherwort.jpg'),
    "Nettles": require('../assets/herbs/nettles.jpg'),
    "Oats": require('../assets/herbs/oats.jpg'),
    "OregonGrapeRoot": require('../assets/herbs/oregon-grape-root.jpg'),
    "Passionflower": require('../assets/herbs/passionflower.jpg'),
    "Peppermint": require('../assets/herbs/peppermint.jpg'),
    "Plantain": require('../assets/herbs/plantain.jpg'),
    "PricklyAsh": require('../assets/herbs/prickly-ash.jpg'),
    "Rose": require('../assets/herbs/rose.jpg'),
    "Rosemary": require('../assets/herbs/rosemary.jpg'),
    "Sage": require('../assets/herbs/sage.jpg'),
    "Schisandra": require('../assets/herbs/schisandra.jpg'),
    "SiberianGinseng": require('../assets/herbs/siberian-ginseng.jpg'),
    "Skullcap": require('../assets/herbs/skullcap.jpg'),
    "Thyme": require('../assets/herbs/thyme.jpg'),
    "Valerian": require('../assets/herbs/valerian.jpg'),
    "Vervain": require('../assets/herbs/vervain.jpg'),
    "WhiteWillow": require('../assets/herbs/white-willow.jpg'),
    "WildLettuce": require('../assets/herbs/wild-lettuce.jpg'),
    "WildYam": require('../assets/herbs/wild-yam.jpg'),
    "WoodBetony": require('../assets/herbs/wood-betony.jpg'),
    "Yarrow": require('../assets/herbs/yarrow.jpg'),
    "YellowDock": require('../assets/herbs/yellow-dock.jpg'),
  }
}